### PR TITLE
feat: add cloud-gpu option

### PR DESCRIPTION
**Pull request by MinhCndS64**

### CODE REVIEW

**Review by danieljimeneznz — CHANGES_REQUESTED** [review]
Don't need to do this, just add `nvidia` to your machine type as an accelerator per https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#machine-type

**Comment by MinhCndS64** [comment]
How do you specify the gcp gpu ? The format [here](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/generic-machine-types) is not very clear.

**Comment by danieljimeneznz** [comment]
> How do you specify the gcp gpu ? The format [here](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/generic-machine-types) is not very clear.

image

**Comment by danieljimeneznz** [comment]
> > How do you specify the gcp gpu ? The format [here](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/generic-machine-types) is not very clear.
> 
> image

Actual resource names for the GPUS: https://cloud.google.com/compute/docs/gpus/add-remove-gpus#adding_gpus_to_existing_vms

**Comment by danieljimeneznz** [comment]
wontfix, see https://github.com/spark-64/workflows/pull/15

**Pull request closed without merging**
